#!/bin/sh

mkdir -p checkout
cd checkout

libccp4_release="8.0.0"
mmdb_release="2.0.22"


if [ -d "libccp4" ]; then
    echo "Found libccp4"
else
    echo "Checking out libccp4"
        curl -L http://ftp.ccp4.ac.uk/opensource/libccp4-$libccp4_release.tar.gz -o libccp4-$libccp4_release.tar.gz
        tar xf libccp4-$libccp4_release.tar.gz
        ln -s libccp4-$libccp4_release libccp4
    echo
fi 


if [ -d "clipper" ]; then
    echo "Found clipper"
else
    echo "Checking out clipper"
    curl -L http://www.ysbl.york.ac.uk/jsd523/clipper-gemmi-wrapper-20240603.tar.gz -o clipper-gemmi-wrapper.tar.gz
    tar xf clipper-gemmi-wrapper.tar.gz
    mv clipper-gemmi-wrapper clipper
    echo
fi 

if [ -d "mmdb2" ]; then
    echo "Found mmdb2"
else
echo "Checking out mmdb2"
      curl -L http://ftp.ccp4.ac.uk/opensource/mmdb2-$mmdb_release.tar.gz -o mmdb2-$mmdb_release.tar.gz
      echo
      echo "Unpacking mmdb2 source"
      tar xf mmdb2-$mmdb_release.tar.gz
      rm -f mmdb2
      ln -s mmdb2-$mmdb_release mmdb2
fi

#if [ -d "ccp4srs" ]; then
#    echo "Found ccp4srs"
#else
#    echo "Checking out ccp4srs"
#    bzr checkout --lightweight  http://fg.oisin.rc-harwell.ac.uk/anonscm/bzr/ccp4srs/trunk/ ccp4srs
#    echo
#fi

if [ -d "gemmi" ]; then
    echo "Found gemmi"
else
echo "Checking out gemmi"
wget https://github.com/project-gemmi/gemmi/archive/refs/tags/v0.6.5.tar.gz
tar xf v0.6.5.tar.gz
mv gemmi-0.6.5 gemmi
echo
fi

if [ -d "fftw-2.1.5" ]; then
    echo "Found fftw-2.1.5"
else

echo "Downloading out fftw-2.1.5"
curl -L http://www.fftw.org/fftw-2.1.5.tar.gz -o fftw-2.1.5.tar.gz
echo
echo "Unpacking fftw-2.1.5"
tar xf fftw-2.1.5.tar.gz
echo
fi
# patch -p0 < ../patches/privateer-emscripten.patch

cd ..