[build-system]
requires = [
  "ChimeraX-BundleBuilder>=1.4.0",
  "ChimeraX-Clipper ~=0.26",
]

[project]
name = "Privateer-for-ChimeraX"
license = { text = "OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)" }
authors = [{ name = "Glycojones Team, University of York", email = "jon.agirre@york.ac.uk" }]
description = "Privateer is a tool for carbohydrate validation, graphical analysis, and visualisation."
dependencies = [
  "ChimeraX-Core ~=1.11.1",
  "ChimeraX-Atomic ~=1.6",
  "ChimeraX-Surface ~=1.0",
  "ChimeraX-Geometry ~=1.0",
  "ChimeraX-UI ~=1.5",
  "ChimeraX-Clipper ~=0.26",
  "pandas",
]
dynamic = ["classifiers", "requires-python", "version"]

[tool.setuptools.dynamic]
version = { attr = "src.__version__"}

[project.readme]
content-type = "text"
text = """Produces an interactive validation report on carbohydrates present within the structure. Hovering over elements of the validation report or clicking on elements can provide more detail. Also provides option to visualise 3D glycan symbols on the model."""

[project.urls]
Home = "https://github.com/glycojones/privateer"


[tool.chimerax]
min-session-version = 1
max-session-version = 1
custom-init = true
categories = ["General"]
classifiers = ["Development Status :: 2 - Pre-Alpha"]

[tool.chimerax.package-data]
"src/data" = [
  "**",
]
"src/docs" = [
  "**",
]

[tool.chimerax.extra-files]
"src/include" = [
  "src/dependencies/**"
]

[tool.chimerax.command.privateer_validation]
category="Validation"
description="Produces a vlidation report from privateer, either displayed in ChimeraX or saved to csv."

[tool.chimerax.command.privateer_glycoblocks]
category="Validation"
description="Generates 3D glycan symbols matching standard SNFGs overlayed with the model in ChimeraX's viewer."

[tool.chimerax.command.privateer_torsion_plot]
category="Validation"
description="Produces a torsion plot of a specified linkage if there is enough data in privateer's torsion database."

[tool.chimerax.tool."Privateer - Validate Carbohydrates"]
category="Validation"
description="Produces a torsion plot of a specified linkage if there is enough data in privateer's torsion database."

[tool.chimerax.extension.privateer_core]
sources = [
  "src/cpp/clipper-glyco_data.cpp",
  "src/cpp/clipper-glyco.cpp",
  "src/cpp/privateer-composition.cpp",
  "src/cpp/privateer-cryo_em.cpp",
  "src/cpp/privateer-lib.cpp",
  "src/cpp/privateer-xray.cpp",
  "src/pybind/privateer-pychimeraX.cpp",
]
include-dirs = [
  "src/dependencies",
  "src/dependencies/gemmi/include",
  "src/dependencies/pybind11/include",
  "src/cpp",
  
]
include-modules = ["chimerax.clipper"]
library-modules = ["chimerax.clipper"]
libraries = [
  "clipper",
  "mmdb2",
  "ccp4",
]
define-macros = [
  "PRIVATEER_CX_EXPORTS",
  "PRIVATEER_VERBOSE",
]

[tool.chimerax.extension.privateer_core.platform.win]
extra-link-args = [
  "/FORCE:MULTIPLE",
]
define-macros = [
  "NOMINMAX",
]

[tool.chimerax.extension.privateer_core.platform.mac]
extra-compile-args = [
  "-fvisibility=hidden",
  "-fvisibility-inlines-hidden",
]
extra-link-args = [
  "-s",
]

[tool.chimerax.extension.privateer_core.platform.linux]
extra-compile-args = [
  "-fvisibility=hidden",
  "-fvisibility-inlines-hidden",
]
extra-link-args = [
  "-s",
]
