import pytest
from privateer import privateer_core as pvt


def test_carbohydrate_structure():
    expected_dir = [
        "CarbohydrateDictionary",
        "CarbohydrateLibrary",
        "CarbohydrateStructure",
        "Conformation",
        "CryoEMData",
        "CrystallographicData",
        "GlycanStructure",
        "GlycosylationComposition",
        "GlycosylationComposition_memsafe",
        "GlycosylationInteractions",
        "OfflineGlycomicsDatabase",
        "OfflineTorsionsDatabase",
        "OfflineTorsionsZScoreDatabase",
        "XRayData",
        "check_monlib_access",
        "furanose_1EV",
        "furanose_1T2",
        "furanose_1TO",
        "furanose_2EV",
        "furanose_2T1",
        "furanose_2T3",
        "furanose_3EV",
        "furanose_3T2",
        "furanose_3T4",
        "furanose_4EV",
        "furanose_4T3",
        "furanose_4TO",
        "furanose_EV1",
        "furanose_EV2",
        "furanose_EV3",
        "furanose_EV4",
        "furanose_EVO",
        "furanose_OEV",
        "furanose_OT1",
        "furanose_OT4",
        "get_annotated_glycans",
        "get_annotated_glycans_hierarchical",
        "print_wurcs",
        "pyranose_14B",
        "pyranose_1C4",
        "pyranose_1E",
        "pyranose_1H2",
        "pyranose_1HO",
        "pyranose_1S3",
        "pyranose_1S5",
        "pyranose_25B",
        "pyranose_2E",
        "pyranose_2H1",
        "pyranose_2H3",
        "pyranose_2SO",
        "pyranose_3E",
        "pyranose_3H2",
        "pyranose_3H4",
        "pyranose_3OB",
        "pyranose_3S1",
        "pyranose_4C1",
        "pyranose_4E",
        "pyranose_4H3",
        "pyranose_4H5",
        "pyranose_5E",
        "pyranose_5H4",
        "pyranose_5HO",
        "pyranose_5S1",
        "pyranose_B14",
        "pyranose_B25",
        "pyranose_B3O",
        "pyranose_E1",
        "pyranose_E2",
        "pyranose_E3",
        "pyranose_E4",
        "pyranose_E5",
        "pyranose_EO",
        "pyranose_OE",
        "pyranose_OH1",
        "pyranose_OH5",
        "pyranose_OS2",
        "write_libraries",
        "write_refmac_keywords",
    ]

    for expected_object in expected_dir:
        assert hasattr(pvt, expected_object)
