
name: Privateer Web App Backend

on:
  push:
    branches: [ "webapp" ]
    paths: 
      - src/privateer/cpp/privateer-bind.cpp

  pull_request:
    branches: [ "webapp" ]
    paths: 
      - src/privateer/cpp/privateer-bind.cpp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
 
    - name: Check out dependencies
      run : |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git pull
        ./emsdk install latest
        ./emsdk activate latest
        cd ..
    
    - name: Check out libraries
      run : |
        ./get_sources
        
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2   
    
    - name: Build
      run : | 
        source ./emsdk/emsdk_env.sh
        emcmake cmake .
        emmake make -j 

    