
name: Privateer Webserver Backend

on:
  push:
    branches: [ "webserver" ]
    paths: 
      - src/privateer/cpp/privateer-bind.cpp

  pull_request:
    branches: [ "webserver" ]
    paths: 
      - src/privateer/cpp/privateer-bind.cpp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
 
    - name: Check out dependencies
      run : |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git pull
        ./emsdk install latest
        ./emsdk activate latest
        cd ..
    
    - name: Check out libraries
      run : |
        git clone https://github.com/Dialpuri/privateer_webserver_dependencies.git 
        cd privateer_webserver_dependencies
        cp -r * ../
        cd .. 
        ls 

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13    
    
    - name: Build
      run : | 
        source ./emsdk/emsdk_env.sh
        emcmake cmake . -D MODE=TESTING
        emmake make -j 

    