
name: Privateer Build

on:
  push:
    branches: [ "master" ]
    paths: 
      - src/**
      - CMakeLists.txt

  pull_request:
    branches: [ "master" ]
    paths: 
      - src/**
      - CMakeLists.txt

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        repo-token: ${{secrets.GITHUB_TOKEN}}
 
    - name: Build
      run : |
        pip install -v . 
    