
name: Privateer Build

on:
  push:
    branches: [ "master" ]
    paths: 
      - src/**
      - CMakeLists.txt

  pull_request:
    branches: [ "master" ]
    paths: 
      - src/**
      - CMakeLists.txt

jobs:
  build:

    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        repo-token: ${{secrets.GITHUB_TOKEN}}
 
    - name: Build
      run : |
        pip install .
    
    - name: Python Tests
      run : |
        export LD_LIBRARY_PATH=privateer_dependencies/lib
        export CLIBD_MON=privateer_dependencies/lib/data/monomers/
        pip install pytest
        pytest tests/test_core.py -m fast
